# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 800)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.is_Input = QtWidgets.QPushButton(Form)
        self.is_Input.setGeometry(QtCore.QRect(520, 280, 100, 40))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(12)
        self.is_Input.setFont(font)
        self.is_Input.setObjectName("is_Input")
        self.no_Input = QtWidgets.QPushButton(Form)
        self.no_Input.setGeometry(QtCore.QRect(520, 340, 100, 40))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(12)
        self.no_Input.setFont(font)
        self.no_Input.setObjectName("no_Input")
        self.begin_yourQA = QtWidgets.QPushButton(Form)
        self.begin_yourQA.setGeometry(QtCore.QRect(330, 220, 100, 40))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(12)
        self.begin_yourQA.setFont(font)
        self.begin_yourQA.setObjectName("begin_yourQA")
        self.choose_Mode = QtWidgets.QLabel(Form)
        self.choose_Mode.setGeometry(QtCore.QRect(490, 140, 160, 60))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(14)
        self.choose_Mode.setFont(font)
        self.choose_Mode.setAlignment(QtCore.Qt.AlignCenter)
        self.choose_Mode.setObjectName("choose_Mode")
        self.inputing_QA = QtWidgets.QLineEdit(Form)
        self.inputing_QA.setGeometry(QtCore.QRect(210, 150, 220, 40))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(12)
        self.inputing_QA.setFont(font)
        self.inputing_QA.setText("")
        self.inputing_QA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputing_QA.setObjectName("inputing_QA")
        self.input_QA = QtWidgets.QLabel(Form)
        self.input_QA.setGeometry(QtCore.QRect(30, 150, 170, 40))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(12)
        self.input_QA.setFont(font)
        self.input_QA.setText("")
        self.input_QA.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input_QA.setObjectName("input_QA")
        self.show_Q = QtWidgets.QLabel(Form)
        self.show_Q.setGeometry(QtCore.QRect(30, 310, 60, 40))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(12)
        self.show_Q.setFont(font)
        self.show_Q.setText("")
        self.show_Q.setAlignment(QtCore.Qt.AlignCenter)
        self.show_Q.setObjectName("show_Q")
        self.Q = QtWidgets.QLabel(Form)
        self.Q.setGeometry(QtCore.QRect(210, 310, 220, 40))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(12)
        self.Q.setFont(font)
        self.Q.setText("")
        self.Q.setAlignment(QtCore.Qt.AlignCenter)
        self.Q.setObjectName("Q")
        self.show_your_A = QtWidgets.QLabel(Form)
        self.show_your_A.setGeometry(QtCore.QRect(30, 370, 100, 40))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(12)
        self.show_your_A.setFont(font)
        self.show_your_A.setText("")
        self.show_your_A.setAlignment(QtCore.Qt.AlignCenter)
        self.show_your_A.setObjectName("show_your_A")
        self.your_A = QtWidgets.QLabel(Form)
        self.your_A.setGeometry(QtCore.QRect(210, 370, 220, 40))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(12)
        self.your_A.setFont(font)
        self.your_A.setText("")
        self.your_A.setAlignment(QtCore.Qt.AlignCenter)
        self.your_A.setObjectName("your_A")
        self.judgement = QtWidgets.QLabel(Form)
        self.judgement.setGeometry(QtCore.QRect(150, 450, 280, 40))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(14)
        self.judgement.setFont(font)
        self.judgement.setText("")
        self.judgement.setAlignment(QtCore.Qt.AlignCenter)
        self.judgement.setObjectName("judgement")
        self.show_sys_A = QtWidgets.QLabel(Form)
        self.show_sys_A.setGeometry(QtCore.QRect(30, 530, 90, 40))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(12)
        self.show_sys_A.setFont(font)
        self.show_sys_A.setText("")
        self.show_sys_A.setAlignment(QtCore.Qt.AlignCenter)
        self.show_sys_A.setObjectName("show_sys_A")
        self.sys_A = QtWidgets.QLabel(Form)
        self.sys_A.setGeometry(QtCore.QRect(210, 530, 220, 200))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(12)
        self.sys_A.setFont(font)
        self.sys_A.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.sys_A.setWordWrap(True)
        self.sys_A.setObjectName("sys_A")
        self.choose_Level = QtWidgets.QLabel(Form)
        self.choose_Level.setGeometry(QtCore.QRect(490, 410, 160, 40))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(14)
        self.choose_Level.setFont(font)
        self.choose_Level.setTextFormat(QtCore.Qt.PlainText)
        self.choose_Level.setAlignment(QtCore.Qt.AlignCenter)
        self.choose_Level.setObjectName("choose_Level")
        self.level_1 = QtWidgets.QPushButton(Form)
        self.level_1.setGeometry(QtCore.QRect(520, 470, 100, 40))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(12)
        self.level_1.setFont(font)
        self.level_1.setObjectName("level_1")
        self.level_2 = QtWidgets.QPushButton(Form)
        self.level_2.setGeometry(QtCore.QRect(520, 530, 100, 40))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(12)
        self.level_2.setFont(font)
        self.level_2.setObjectName("level_2")
        self.level_3 = QtWidgets.QPushButton(Form)
        self.level_3.setGeometry(QtCore.QRect(520, 590, 100, 40))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(12)
        self.level_3.setFont(font)
        self.level_3.setObjectName("level_3")
        self.Again = QtWidgets.QPushButton(Form)
        self.Again.setGeometry(QtCore.QRect(450, 730, 100, 40))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(12)
        self.Again.setFont(font)
        self.Again.setObjectName("Again")
        self.Close = QtWidgets.QPushButton(Form)
        self.Close.setGeometry(QtCore.QRect(590, 730, 100, 40))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(12)
        self.Close.setFont(font)
        self.Close.setObjectName("Close")
        self.is_choose = QtWidgets.QPushButton(Form)
        self.is_choose.setGeometry(QtCore.QRect(520, 220, 100, 40))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(12)
        self.is_choose.setFont(font)
        self.is_choose.setObjectName("is_choose")
        self.welcome = QtWidgets.QLabel(Form)
        self.welcome.setGeometry(QtCore.QRect(200, 30, 440, 80))
        font = QtGui.QFont()
        font.setFamily("张海山锐谐体")
        font.setPointSize(14)
        self.welcome.setFont(font)
        self.welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome.setObjectName("welcome")
        self.decorate = QtWidgets.QLabel(Form)
        self.decorate.setGeometry(QtCore.QRect(30, 20, 120, 100))
        self.decorate.setObjectName("decorate")

        self.retranslateUi(Form)
        self.Close.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.is_Input.setText(_translate("Form", "手动输入"))
        self.no_Input.setText(_translate("Form", "自动生成"))
        self.begin_yourQA.setText(_translate("Form", "确认"))
        self.choose_Mode.setText(_translate("Form", "游戏模式"))
        self.sys_A.setText(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.choose_Level.setText(_translate("Form", "游戏难度"))
        self.level_1.setText(_translate("Form", "初级"))
        self.level_2.setText(_translate("Form", "中级"))
        self.level_3.setText(_translate("Form", "高级"))
        self.Again.setText(_translate("Form", "我还要玩"))
        self.Close.setText(_translate("Form", "不玩啦"))
        self.is_choose.setText(_translate("Form", "题库选题"))
        self.welcome.setText(_translate("Form", "欢迎来到火柴等式！请先选择游戏模式~"))
        self.decorate.setText(_translate("Form", "TextLabel"))
